spring.application.name=blog-application

spring.main.banner-mode=off

spring.datasource.url=jdbc:postgresql://localhost:5432/blog_app_db
spring.datasource.username=postgres
spring.datasource.password=Ridwan@63
spring.jpa.hibernate.ddl-auto=update